export const SET_FLIGHT_SEARCH_RESULT = "SET_FLIGHT_SEARCH_RESULT";

export const SET_FLIGHT_FILTERED_RESULT = "SET_FLIGHT_FILTERED_RESULT";

export const SET_MIN_MAX_FARE = "SET_MIN_MAX_FARE";

export const SET_FLIGHT_FILTER_ORDER = "SET_FLIGHT_FILTER_ORDER";